[package]
name = "wasmonkey"
version = "0.1.9"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Patch a WASM object file to replace a set of exported functions with imported functions from another library"
license = "ISC"
homepage = "https://github.com/jedisct1/wasmonkey"
repository = "https://github.com/jedisct1/wasmonkey"
categories = ["wasm"]
edition = "2018"

[dependencies]
clap = "2.33"
failure = "0.1"
goblin = "0.2"
lazy_static = "1.4"
parity-wasm = "0.41"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
siphasher = "0.3"
xfailure = "0.1"
