[package]
name = "wasmonkey"
version = "0.1.11"
authors = ["Frank Denis <github@pureftpd.org>"]
description = "Patch a WASM object file to replace a set of exported functions with imported functions from another library"
license = "ISC"
homepage = "https://github.com/jedisct1/wasmonkey"
repository = "https://github.com/jedisct1/wasmonkey"
categories = ["wasm"]
edition = "2018"

[dependencies]
clap = "2.33.3"
failure = "0.1.8"
goblin = "0.4.0"
lazy_static = "1.4.0"
parity-wasm = "0.42.1"
serde = "1.0.115"
serde_derive = "1.0.115"
serde_json = "1.0.57"
siphasher = "0.3.3"
xfailure = "0.1.0"
